
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smd?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 80

#屏蔽接口文档
#knife4j:
#  production: true

## 开启Swagger的Basic认证功能,默认是false
knife4j:
  basic:
    enable: true
    username: admin   # Basic认证用户名
    password: 123  # Basic认证密码